steps:
  count: 30
  delay: 100
floors:
  count: 4
elevators:
 count: 2
hotel:
  elevator:
    capacity: 3
  spawn-probability:
    ground: 0.65
    other: 0.65
  display:
    column-width:
      floor: 5
      elevator: 24
      persons: 20
